name       : mtpaint
version    : 3.40
release    : 1
source     :
    - http://tenet.dl.sourceforge.net/project/mtpaint/mtpaint/3.40/mtpaint-3.40.tar.bz2 : ef321d2b404839c7b909bdf5283eb22a37fbdd35b4cc9e380ddc400573d7c890
license    : GPL-5.0
component  : multimedia.graphics
summary    : mtPaint is a painting program designed for creating icons and pixel-based artwork
description: |
    mtPaint is a painting program designed for creating icons and pixel-based artwork
builddeps  :
    - pkgconfig(atk)
    - pkgconfig(freetype2)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libtiff-4)
    - pkgconfig(pangocairo)
    - pkgconfig(zlib)
    - giflib-devel
    - libjpeg-turbo-devel
setup      : |
    %configure --prefix=/usr --disable-static \
               GIF jpeg lcms2 man tiff
build      : |
    %make
install    : |
    %make_install
