name       : mtpaint
version    : 3.4
release    : 4
source     :
    - http://tenet.dl.sourceforge.net/project/mtpaint/mtpaint/3.40/mtpaint-3.40.tar.bz2 : ef321d2b404839c7b909bdf5283eb22a37fbdd35b4cc9e380ddc400573d7c890
license    : GPL-3.0
component  : multimedia.graphics
summary    : mtPaint is a painting program designed for creating icons and pixel-based artwork
description: |
    mtPaint is a painting program designed for creating icons and pixel-based artwork
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libtiff-4)
    - giflib-devel
setup      : |
    %patch -p1 < $pkgfiles/giflib5.diff

    %configure --disable-static GIF jpeg lcms2 man tiff
build      : |
    %make
install    : |
    %make_install
