name       : mtpaint
version    : '3.50'
release    : 10
source     :
    - https://sourceforge.net/projects/mtpaint/files/mtpaint/3.50/mtpaint-3.50.tar.bz2/download : 695cea10c428a8f122ed59beee5ffa49dcdcba8d88a4790eaf3c64fd7c73d6ac
license    : GPL-3.0-or-later
component  : multimedia.graphics
summary    : mtPaint is a painting program designed for creating icons and pixel-based artwork
description: |
    mtPaint is a painting program designed for creating icons and pixel-based artwork
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(lcms2)
    - pkgconfig(libpng)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libtiff-4)
    - pkgconfig(libwebp)
    - giflib-devel
setup      : |
    %configure gtk3 GIF intl jpeg lcms2 man tiff webp
build      : |
    %make
install    : |
    %make_install
